### ISSUE TITLE
how to remove confirm?

### ISSUE THREAD

**Issue by HyunwooP** [jarden-digital/react-native-pincode#101]
status={'choose'} 
how to remove confirm status?

I only want one input pincode and next action

**Comment by Alale66** [comment]
I have the same question.

**Comment by kdbcinco-cs** [comment]
Why would you want it that way? `choose` mode is for entering a **new** pin. The confirm part is there to ensure that the user has actually entered the right pin. Much like how password/confirm password works.

If you really want it to only ask for pin once, with no confirmation, you can render the `PinCodeChoose` component yourself.

**Comment by Haskkor** [comment]
Hi,

I agree with @kdbcinco-cs . 
We don't really see the use case and won't have time to implement such a change. 
You're more than welcome to do a PR though :)

Cheers,
Jeremy
