### ISSUE TITLE
TouchID dialog sometimes get hidden

### ISSUE THREAD

**Issue by kdbcinco-cs** [jarden-digital/react-native-pincode#109]
React Native: `0.57.8`
react-native-keychain: `3.0.0`
react-native-touch-id: `4.4.1`
Build: Release

The TouchID dialog sometimes get hidden somewhere. This happens for both Android and iOS but the behavior has more impact on iOS. On iOS, opening the App Switcher using the Accessibility button does not work because the dialog is still active. If you tap the home button on iOS, the dialog will show up for a bit then get dismissed. I can also enter the PIN manually during this quirky behavior of the dialog.

**Comment by Haskkor** [comment]
Hi,

Sorry for the delay.
I have troubles reproducing this. I'll keep on trying but I hope someone else will be able to reproduce it :)

Cheers,
Jeremy

**Comment by Haskkor** [comment]
I've experienced this issue but it seems fixed in the latest version.
