### ISSUE TITLE
Haptic Feedback

### ISSUE THREAD

**Issue by agnjkafgh** [jarden-digital/react-native-pincode#111]
I was wondering if it would be possible to enable haptic feedback (vibration) onPress of each number button.

**Comment by Haskkor** [comment]
Hi,

Sorry for the delay.
It's a good idea. I don't know when I'll have time to work on this though so feel free to do a PR :)

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Waiting for a PR.
