### ISSUE TITLE
Question: Does it really safe savind the amount of attempts on `AsyncStorage`?

### ISSUE THREAD

**Issue by danilowoz** [jarden-digital/react-native-pincode#119]
I have some doubts about this approach, couldn't someone just edit the number of attempts and reset it?

**Comment by Haskkor** [comment]
Hi,

No it's not safe. It's not trivial to modify the async storage but we're a finance company so we don't use it that way anyway. 
We provide a `handleResultEnterPin` that you can use to store the pin and the attempts the way you see fit. 
But if the data that you're handling is really sensitive, you might have to tweak it even more...

Cheers, 
Jeremy

**Comment by zyofeng** [comment]
My understanding is any attempt at securing client side is more or less futile when it comes to a determined hacker. If you want a really secure system you would be hashing the pins and sending it to the server side for verification and storing the no. of attempts.

Anything stored on the client side needs to be viewed as insecure.

**Comment by danilowoz** [comment]
Really thanks for your answers.
As I have been working in a banking app, I came here to get some ideas to build my own Pincode page and this issue came up. One approach I'm planning to build, it stores the attempt times and date time to unlock the screen on Keychain (ios) without any request to the server. 

Do you guys think that is enough? Let me know your thoughts about it.

**Comment by zyofeng** [comment]
Short answer: that should be sufficient. 
Long answer: you would need to harden the rest of the system to make sure they are not prone to brutal force attacks should a malicious user manage to bypass your no. of attempts restriction and/or limit the attack surface when they do. e.g. grant only read permission (viewing statement) and require secondary verification (SMS verification) for other sensitive operations (transacting money)

**Comment by danilowoz** [comment]
@zyofeng Thanks again! 
That helped me a lot
