### ISSUE TITLE
Keyboard alignment versions in Android

### ISSUE THREAD

**Issue by k-varma** [jarden-digital/react-native-pincode#121]
I am updating my APp from 0.56.0 to 0.60.5, When updatig the feature is working fine, Earlier the Keyboard is center aligned, But it is not aligned properly, It is showing in right. Do i need to do any changes ?

**Comment by kiran-mantana** [comment]
I request close this as the information i Have given is wrong, I am creating a new request, Please close this.

**Comment by Haskkor** [comment]
Hi,

Okay! Feel free to reopen it if needed.

Cheers,
Jeremy
