### ISSUE TITLE
Number Board Alignment issue in One Plus 7

### ISSUE THREAD

**Issue by kiran-mantana** [jarden-digital/react-native-pincode#122]
I am using Pincode in my project, It was working fine in some devices, Today when tried to run the app in One Plus 7, I am getting alignment issue, Attaching the screenshot 

I am using 

"@haskkor/react-native-pincode": "^1.21.1",
    "react-native": "^0.60.5",

![Numberpad](https://user-images.githubusercontent.com/44198435/66185941-90cbb000-e69e-11e9-80d1-7f0157926d9d.jpeg)

**Comment by Haskkor** [comment]
Hi,

Would you have more info to help me (css inspect...)? I can't reproduce so it's hard to figure out what's happening :)

**Comment by kiran-mantana** [comment]
render() {
        return (
            <View style={styles.container}>
                <StatusBar
                    backgroundColor="#1FA1AA"
                />

                {/* {!this.props.isSetNewPasscode && this.state.IsTouchIdSupported ?
                    <TouchableOpacity onPress={() => this._authenticateUsingTouchID()}>
                        <Text style={{ color: 'white', fontSize: 18, textAlign: 'center', fontWeight: 'bold' }}>Authenticate With Touch ID</Text>
                    </TouchableOpacity> : <View />} */}

                <PINCode
                    status={this.props.isSetNewPasscode ? 'choose' : 'enter'}
                    handleResultEnterPin={pinCode => this.handleResultEnterPin(pinCode)}
                    storePin={(pin) => {
                        this.handleResultEnterPin(pin)
                    }}
                    touchIDDisabled={true}
                    titleChoose={'Choose a PinCode'}
                    subtitleChoose={'to keep your information secure'}
                    styleMainContainer={{
                        flex: 0.8,
                       // paddingTop: 5,
                        justifyContent: 'center',
                        alignItems: 'center',
                    }}
                    stylePinCodeButtonCircle={{
                        alignItems: 'center',
                        justifyContent: 'center',
                        width: 16 * 4,
                        height: 16 * 4,
                        backgroundColor: 'rgba(250,250,250 ,1)',
                        borderRadius: 16 * 2,
                        margin: 10,
                        borderColor: "rgba(119, 119, 119,0.3)",
                        borderWidth: 1
                    }}
                    stylePinCodeColorTitle="#FFFFFF"
                    stylePinCodeColorTitleError="#FFFFFF"
                    stylePinCodeColorSubtitleError="#FFFFFF"
                    colorPassword="#32BEDE"
                    stylePinCodeButtonNumber="#777777"
                    stylePinCodeMainContainer={{
                        flex: 1,
                        alignItems: 'center',
                        height: 40
                    }}
                    stylePinCodeRowButtons={{
                        justifyContent: 'center',
                        alignItems: 'center',
                        width: '100%',
                        height: 16 * 5.5
                    }}
                    stylePinCodeTextButtonCircle={{
                        fontSize: 16 * 2,
                        fontWeight: '200'
                    }}
                    stylePinCodeTextSubtitle={{
                        fontSize: 15,
                        fontWeight: '200',
                        lineHeight: 0
                    }}
                    stylePinCodeColorSubtitle="#fff"
                    stylePinCodeHiddenPasswordCircle={{
                        flexDirection: 'row',
                        width: width,
                        height: height * 0.06,
                        justifyContent: 'center',
                        alignItems: 'center',
                        marginTop: -(height * 0.03)
                    }}
                />

            </View>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#1FA1AA',
    },
})

**Comment by Haskkor** [comment]
Can't see anything wrong like that.
I'll give it a try when I get a chance. 
Looks like a css issue to me though
