### ISSUE TITLE
Title sentence not passed to titleComponent

### ISSUE THREAD

**Issue by alberthitanaya** [jarden-digital/react-native-pincode#124]
On L623 of PinCode.tsx

`{this.props.titleComponent
                ? this.props.titleComponent()
                : this.renderTitle(
                  colorTitle,
                  opacityTitle,
                  attemptFailed,
                  showError
                )}
              {this.props.subtitleComponent
                ? this.props.subtitleComponent()
                : this.renderSubtitle(
                  colorSubtitle,
                  opacityTitle,
                  attemptFailed,
                  showError
                )}`

Does this.props.sentenceTitle and subTitle need to be passed into the custom components in order to use a custom component?

**Comment by Haskkor** [comment]
Hey,

Sorry for the delay I missed that. No you should be able to just use the custom component...
Is it not displaying your component or just the text?

**Comment by Haskkor** [comment]
Tested and ok

**Comment by allindeveloper** [comment]
Hi @jeremy-farnault 
Please how can i dynamically change the titleComponent to render content for the initial step and confirm step.
My implementation is not working..

```js
titleComponent={()=>(
         <>
                <Text color={COLORS.WHITE} p size={30}>{` ${pinStatus==="initial"? "Create FlipX Pin":"Confirm"}`}</Text>
                <Space top={10} />
                </>
          )}```

**Comment by allindeveloper** [comment]
Or is there a hook to return the current step/page ?
