### ISSUE TITLE
New attempt after incorrect attempt is too slow

### ISSUE THREAD

**Issue by kkaushik90f** [jarden-digital/react-native-pincode#126]
Perhaps `await delay(3000);` should actually be `await delay(300);` in this line:

https://github.com/jarden-digital/react-native-pincode/blob/master/src/PinCode.tsx#L153

Or the input should be disabled for that duration. Otherwise if the user keeps typing after a failed attempt, it messes it up.

**Comment by Haskkor** [comment]
Hi,

I'll provide a prop to customize this in the next version. 
Feel free to make it a PR if you want it faster 😃 .

Cheers,
Jeremy
