### ISSUE TITLE
does touchIDDisabled={true} work?

### ISSUE THREAD

**Issue by tststs** [jarden-digital/react-native-pincode#128]
FaceId is enabled on an iPhone X. If i set `touchIDDisabled={true}` it still shows FaceId. Am i using it wrong?

Greetings

**Comment by Haskkor** [comment]
Hey,

Sorry for the delay.
I've just tried with a really simple implementation.

```
        <PINCode
          status={'enter'}
          touchIDDisabled={true}
        />
```
doesn't show faceID

```
        <PINCode
          status={'enter'}
        />
```
shows face ID

Can you please provide your implementation because I can't reproduce your issue.

Cheers,
Jeremy

**Comment by tststs** [comment]
Hey! I wrapped the component and forgot to also pass touchIDDisabled prop... Sorry for the inconvenience. :)
