### ISSUE TITLE
Where i can get grid.unit for applying it in setting ?

### ISSUE THREAD

**Issue by cryptozoidberg** [jarden-digital/react-native-pincode#131]
Hi PinCode!
If I want to setup styleLockScreenButton, in documentations said: 

> 

styleLockScreenButton | Button of the lock screen | backgroundColor: colors.turquoise, borderRadius: grid.border, paddingLeft: grid.unit * 2, paddingRight: grid.unit * 2, paddingBottom: grid.unit, paddingTop: grid.unit
-- | -- | --

I was wondering, where I can get "grid.unit", to use it with other default options?

**Comment by Haskkor** [comment]
Hi :)

It's in the `grid.ts` file. 
I'm not exposing it though. It's equal to 16px :)
