### ISSUE TITLE
Update Keychain dependency

### ISSUE THREAD

**Issue by greenbue** [jarden-digital/react-native-pincode#136]
https://github.com/oblador/react-native-keychain/releases/tag/v6.0.0

Please bump the keychain dependency to the latest

**Comment by Haskkor** [comment]
Hi, 

When bumping keychain in the past, I remember it causing troubles to some users. 
I'll try to find the previous issues when I get the time.

**Comment by greenbue** [comment]
Hi, sorry actually there is currently an issue with Keychain before this can be bumped.

https://github.com/jarden-digital/react-native-pincode/issues/137

**Comment by Haskkor** [comment]
Just merged a PR upgrading the library :)
Thanks
