### ISSUE TITLE
Protected against devices without TouchID

### ISSUE THREAD

**Issue by pke** [jarden-digital/react-native-pincode#141]
Line https://github.com/jarden-digital/react-native-pincode/blob/master/src/PinCodeEnter.tsx#L141

should be protected agains `TouchID` beeing `undefined` on devices without such capabilities, to prevent a JS exception when accessing `TouchID`.

**Comment by Haskkor** [comment]
Yep sure. I'll fix this in next version. Thanks!

**Comment by Haskkor** [comment]
Done :)
