### ISSUE TITLE
"Enter Iphone passcode for "Appname" To unlock your application" screen

### ISSUE THREAD

**Issue by JayDJayG** [jarden-digital/react-native-pincode#143]
When I open my app instead of seeing the numeric default Pin-lock screen that this library provides, another one pops up with the the following title:  

"Enter Iphone passcode for "Appname" To unlock your application"

If I feed the right pincode on this screen I am able to unlock my screen. 

How can I make for the default screen to pop up?

**Comment by JayDJayG** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-10 at 20 24 12](https://user-images.githubusercontent.com/22334735/84334784-d6f3e000-ab58-11ea-8e17-5da62da47065.png)

**Comment by szlezak** [comment]
I guess this one is from simulator. There isn't touchID set up, it just simulating it, so you are able to type there anything and the touchID will be correct. After that, you will be able to pass pin code screen

**Comment by Haskkor** [comment]
Yep exacly! :) Thanks for the explanation
