### ISSUE TITLE
this.props.emptyColumnComponent is not a function

### ISSUE THREAD

**Issue by krishnadas89** [jarden-digital/react-native-pincode#145]
![image](https://user-images.githubusercontent.com/7599778/86110069-b9c08a80-bae2-11ea-9b8c-25631478725a.png)

https://github.com/jarden-digital/react-native-pincode/blob/45d4873d8dca93d69b1e72a29e6683e35a69cd18/dist/src/PinCode.js#L386

After you have updated and added the above lines I am getting error(attached above) when i try run my app after installing react-native-call-detection using yarn add. Seems like yarn add automatically updates other packages as well. But for all other packages there is nothing breaking. 

I even tried passing launchTouchID in the props as null but got same error.

For now I manually had to revert the above line as it was before to run my app. Could you please look into this and suggest if I am missing on something or the issue is at your end.

Regards,
Krishna

**Comment by Haskkor** [comment]
Hi 😄 
Are you passing your own custom component in the `bottomLeftComponent` property?
Thanks!
Jeremy

**Comment by greenbue** [comment]
> Hi 
> Are you passing your own custom component in the `bottomLeftComponent` property?
> Thanks!
> Jeremy

Yes, is this the issue?
