### ISSUE TITLE
RNKeychainManager.setInternetCredentialsForServer got 7 arguments, expected 6

### ISSUE THREAD

**Issue by tststs** [jarden-digital/react-native-pincode#146]
Hey there!

I tried upgrading to `1.22.3` and `react-native-keychain@^6.1.1`.
When setting a new pin code the mentioned error pops up and i'm unable to set a pin code.

I had a look into both the code of this module and react-native-keychain and there is absolutely no sign of a function which even would take that much arguments.

Any idea what may cause this issue?

Thanks in advance!

**Comment by Haskkor** [comment]
Hi!

We had this one https://github.com/jarden-digital/react-native-pincode/issues/123 (different number of arguments 🙈 )
And here which is newer: https://github.com/jarden-digital/react-native-pincode/issues/136 . 
Could you try to see if the `solution` provided in the latest one works for you? If so, I'll have to find a better way...

Cheers,
Jeremy
