### ISSUE TITLE
React Native Vector Icons issue toolbar-android could not be found

### ISSUE THREAD

**Issue by emmastead** [jarden-digital/react-native-pincode#147]
I believe that the react-native-vector-icons dependency needs to be updated to 7.0.0 as react-native-vector-icons have removed Icon.AndroidToolbar which is causing the issue. See here : 
https://github.com/oblador/react-native-vector-icons/issues/1193

**Comment by ashotosipyan** [comment]
Does anyone see this comments? your package is not working because of very stupid reason, this problem must be solved as soon as possible!

**Comment by Haskkor** [comment]
Hi,
So sorry for that. I was playing with the GitHub iOS app and managed to get rid of all notifications...so I missed this.
It's merged and will be released today.
Cheers
