### ISSUE TITLE
Using TouchID return undefined 

### ISSUE THREAD

**Issue by rahmath30** [jarden-digital/react-native-pincode#151]
<PINCode
                    status={AppLockStatus ? 'enter' : 'choose'} 
                    endProcessFunction={(pin) => this.onFinish(pin)}
                    storePin={(pin) => { console.log('pin ', pin)}}
                />

the endProcessFuntion returns undefined only for the auth of touch ID. enter pin is working fine. please help me on this

**Comment by Haskkor** [comment]
Hi,

```
      await TouchID.authenticate(
        this.props.touchIDSentence,
        Object.assign({}, optionalConfigObject, {
          title: this.props.touchIDTitle
        })
      ).then((success: any) => {
        this.endProcess(this.props.storedPin || this.keyChainResult)
      })
```

The end process function triggered by the TouchId returns either 'storedPin' that you can provide or the value stored in KeyChain if you store it there.
Are you doing any of those things?
