### ISSUE TITLE
null is not an object (evaluating 'RNKeychainManager.SECURITY_LEVEL_ANY')

### ISSUE THREAD

**Issue by tskorupka** [jarden-digital/react-native-pincode#66]
`null is not an object (evaluating 'RNKeychainManager.SECURITY_LEVEL_ANY')`

dependencies:
`@haskkor/react-native-pincode#1.13.0`
`react-native-keychain#3.1.1`

![Image](https://i.imgur.com/uTybdnq.png)

**Comment by JakubSys** [comment]
I've got same issue

**Comment by Haskkor** [comment]
Hi there,

I can't reproduce it. Did you link the libraries etc?

Cheers,
Jeremy

**Comment by JakubSys** [comment]
Well, I've just reinstalled that today and its working, at monday I did it several times and it didnt work. Now working just fine.

**Comment by Haskkor** [comment]
Thanks for the feedback.
I'll leave this open and keep on investigating.

Cheers,
Jeremy

**Comment by tskorupka** [comment]
@Haskkor try without permissions for fingerprint I think that fixed it in my case.

**Comment by codedadysolutions** [comment]
still it shows the same error

**Comment by wuno** [comment]
On a fresh install I have this same issue. For my use case I do not want to use any of the other features. I just need a clean way of accepting a pin from a user. 

The flow I am trying to accomplish is like this, 

**The first time a user uses the application -**

- User enters a pin. 
- User verifies the pin a second time. 
- I never store the pin on the phone and instead I encrypt some data in the mobile app with the pin. 

**The next time the user uses the mobile app I request their pin to decrypt their saved data -**

- Once the user's data is decrypted, they have access to use the mobile application as a logged in user. 

On a fresh install, I see the error mentioned above, 

> Cannot read property 'SECURITY_LEVEL_ANY' of undefined

Example of usage, 

> npm install --save @haskkor/react-native-pincode

```
import PINCode from '@haskkor/react-native-pincode';

class Auth extends Component {
render() {
    return (
      <Container style={styles.container}>
        <PINCode
          status="enter"
          finishProcess={async () => {
            this.props.navigation.navigate('Account');
          }}
          maxAttempts={3}
        />
      </Container>
    );
  }
}
```

**Comment by Haskkor** [comment]
Hey, 

I'm so sorry to read that as I can't reproduce. Could any of you try to use a previous version (1.12.2 might be a good one) and tell me if it fixes the issue? If so, I'll rollback the changes and keep on investigating.

Thanks,
Jeremy

**Comment by athulmurali** [comment]
I installed it today and facing the same issue. 

Once, I import the package I am getting this issue. 
` import PINCode from '@haskkor/react-native-pincode'
`

**Comment by kevinwolfcr** [comment]
@Haskkor this is because this package is requiring `react-native-keychain@^3.0.0-rc.3`, I created PR #72 locking the version to the last stable version.

**Comment by Haskkor** [comment]
Thanks for that.
It's merged. Help it'll fix it for you all.

**Comment by nileshprajapati007444** [comment]
I have same error. can anyone help me to fix it ?

**Comment by kevinwolfcr** [comment]
> I have the same error. can anyone help me to fix it?

It is weird since dependency was locked on the PR I opened.

- May you have a `package-lock.json` or a `yarn.lock` that may be still downloading the buggy version?
- Did you upgrade to latest version of `react-native-pincode`?

**Comment by TchernyavskyDaniil** [comment]
I have same issue for new version of react-native-pincode

**Comment by gokulanath** [comment]
I have the same issue in v1.21.1

**Comment by k-varma** [comment]
I am getting same is in 0.61.0, But it was working fine in the same version yesterday, i have did some changes for iOS and reverted them, but still get the issue

**Comment by thaiphan** [comment]
Have you guys tried running the following commands?

```
yarn add react-native-keychain
cd ios
pod install
```

**Comment by akhilsanker** [comment]
Hi @wuno ,
Have you solved the error?
I am facing the same error.

**Comment by akhilsanker** [comment]
Any solution?

**Comment by akhilsanker** [comment]
@tskorupka 
Is this is working component??

**Comment by Haskkor** [comment]
Hi @akhilsanker 
I'm really sorry to hear that you can't make it work. It's working fine for us and it's used by 50+ other repos...
I really don't know why some of you are experiencing this issue...

**Comment by fonderkin** [comment]
Same problem
react-native-keychain 3.1.3
react-native 0.61.5
react-native-pincode 1.21.1 "

**Comment by ftlno** [comment]
Same problem..
"react-native-keychain": "^4.0.5",
"react-native": "0.61.5",

I have tried automatic, cocoapods nad manual install. iOS is building successfully.  But when I `import * as Keychain from 'react-native-keychain';` in RN, I am getting `null is not an object (evaluating 'RNKeychainManager.SECURITY_LEVEL_ANY')`

Please help :)

**Comment by EliaFederico** [comment]
It is because last version (1.21.1) did update again the dependency 'react-native-keychain' to 3.1.3. 

I solved this problem downgrading this library to version 1.21.0 which uses 'react-native-keychain' v3.0.0

**Comment by Haskkor** [comment]
Is this solution working ok for all of you?
If so I'll downgrade keychain back to v3.0.0 😄 
Thanks @EliaFederico

**Comment by cihanbas** [comment]
I had same problem but when i installed react-native-keychain then  this problem solved

**Comment by Haskkor** [comment]
I at last experienced this issue when upgrading keychain to 5.0.1.
However following this: https://github.com/oblador/react-native-keychain/issues/221
And then the instructions on keychain: 
```
Run yarn add react-native-keychain

1 a. Only for React Native <= 0.59: $ react-native link react-native-keychain and check MainApplication.java to verify the package was added. See manual installation below if you have issues with react-native link.
```
it fixed itself.
I don't know what else can cause this.
