### ISSUE TITLE
How to get it working with Expo?

### ISSUE THREAD

**Issue by grinono** [jarden-digital/react-native-pincode#80]
Do you have a quick fix to let this component work with the expoJS stack. the async storage linking is not possible without detaching. Would like to keep the expo perks :-)

why not set import { AsyncStorage } from "react-native" instead of community version?

**Comment by Haskkor** [comment]
Hi,

I can't think of a simple solution at the moment. If you have an idea don't hesitate to create a PR :)

Cheers,
Jeremy

**Comment by scalalang2** [comment]
**1. Expo does not support NativeModule.** 
Expo does not support react NativeModules from birth. So. you can not use the packages that requires using NativeModules.

I don't recommend you to build apps with expo for a such reason.

**2. Old version of AsyncStorage is deprecated.**
```
import {AsyncStorage} from 'react-native'
```
Above way of using AsyncStorage is deprecated. So you should use community version instead.
