### ISSUE TITLE
TouchId not working for IOS

### ISSUE THREAD

**Issue by abhirup03** [jarden-digital/react-native-pincode#86]
I have tested the code in android devices it works fine though it lags. But when i try to access my app using touch-id in iPhone it doesn't navigate to the particular page and stays in the same pincode screen. While i try to access the app using pincode on ios it works fine and navigates appropriately. Can someone help me out figuring what might be the issue?

**Comment by Haskkor** [comment]
Hi,

Could you please post your implementation?

Cheers,
Jeremy
