### ISSUE TITLE
[Proposal] - Add features for changing pincode.

### ISSUE THREAD

**Issue by scalalang2** [jarden-digital/react-native-pincode#93]
The change of pincode are a common feature in most of mobile applications.
Users must proceed following steps to change their pincode.

Users must enter the stored pin code. If the user enter the pin code correctly, app will be moved to the screen where you enter the new pin code and, if not app will show a warning message and require users to enter correct pin code again.

**Comment by Haskkor** [comment]
Hi!

Sorry for the delay :).
I like the idea but I'm pretty sure that it's already doable by playing with the statuses.
I would:
* Use the blank space button to display a 'Change pin' button
* On click: display the PinCode in 'enter' mode with a title indicating that the current pincode is requested
* On success: display the PinCode in 'choose' mode to create a new one
* On fail: display a new screen with the warning an a link to go the PinCode on 'enter' mode again
I may be wrong but I don't see why it wouldn't be doable with the current component.

Cheers :)
Jeremy
