### ISSUE TITLE
Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by mrmikopi** [jarden-digital/react-native-pincode#96]
I had a time which i could run pincode in Android, but got this error in IOS. 
Now, it is much worse and i have the error on both. I don't know what causes this. Probably it is about npm modules and links. I've tried removing node modules and reinstalling, linking packages. It failed again.
I have a simple code that i can share if it helps any:

```
import React from 'react';
import { ScrollView } from 'react-native';
import {PINCode} from '@haskkor/react-native-pincode';
import AsyncStorage from '@react-native-community/async-storage';

export default class PinScreen extends React.Component {
    static navigationOptions = { 
           title: 'Pin',
     };

     render() {
         return (
             <ScrollView>
                 <PINCode status={this.props.navigation.getParam('action', 'enter')}/>
             </ScrollView>
         );
     }
}
```

**Comment by Haskkor** [comment]
Hi,

Sorry to hear that. 

I can't reproduce this error unfortunately. From what I read online it seems that most of the time it's related with the way you export/import components.

https://stackoverflow.com/questions/47825540/react-native-invariant-violation-element-type-is-invalid?rq=1
https://github.com/facebook/react-native/issues/16332
https://github.com/facebook/react/issues/9249
https://stackoverflow.com/questions/34130539/uncaught-error-invariant-violation-element-type-is-invalid-expected-a-string

Did you check this? If so I hope someone else will be able to reproduce this error but I'll keep on trying.

Cheers,
Jeremy
