### ISSUE TITLE
[Proposal] Allow for Icons to be a props component

### ISSUE THREAD

**Issue by galimpian** [jarden-digital/react-native-pincode#99]
Currently I use Fontaweome for icons and with this package I am forced to use material icon, is there a way to offer flexibility to send in a component props for icons?

**Comment by Haskkor** [comment]
Hi,

Yes good idea. I'm closing the issue as you made the PR.

Cheers,
Jeremy

**Comment by Haskkor** [comment]
It's published in version 1.41.0
